### ISSUE TITLE
Mouse And Keyboard Are Not Working After Compilation Of  Program

### ISSUE THREAD

**Issue by Akshaymeshram1701** [vineetchoudhary/TurboCPP#36]
please solve this issue mouse and keyboard are not work after compiling a program.also many time declaration problem occurs.

**Comment by suman45-hub** [comment]
Please solve this issue mouse and keyboard are not work after compiling a program.Also many time declaration problem occurs.

**Comment by suman45-hub** [comment]
> Please solve this issue mouse and keyboard are not work after compiling a program.Also many time declaration problem occurs.

Please solve it.I a facing a lot of problem through this.

**Comment by iota-008** [comment]
> please solve this issue mouse and keyboard are not work after compiling a program.also many time declaration problem occurs.

JUST CHANGE THE EDITOR USE **VISUAL STUDIO CODE** INSTEAD IT IS MORE COMFORTABLE .
