### ISSUE TITLE
Mouse stops working 

### ISSUE THREAD

**Issue by Etuna101** [vineetchoudhary/TurboCPP#6]
after a few compilations the mouse stops working within the TurboC windows until you press "alt F", "left" and "Enter" then it becomes continuous issue after you keep redoing the same process again and a again.... is there no way to solve it permanently??

**Comment by vineetchoudhary** [comment]
Hi, Please check alternative solution here - 
https://developerinsider.co/after-sometime-mouse-pointer-is-getting-stuck/
